package com.github.xandergos.terraindiffusionmc.world;

import com.github.xandergos.terraindiffusionmc.block.LayeredBlock;
import com.github.xandergos.terraindiffusionmc.block.ModBlocks;
import com.github.xandergos.terraindiffusionmc.config.TerrainDiffusionConfig;
import com.github.xandergos.terraindiffusionmc.pipeline.LocalTerrainProvider;
import com.github.xandergos.terraindiffusionmc.pipeline.LocalTerrainProvider.HeightmapData;
import com.github.xandergos.terraindiffusionmc.pipeline.MassFluxRiverCarver;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.ChunkPos;
import net.minecraft.world.StructureWorldAccess;
import net.minecraft.world.World;
import net.minecraft.world.chunk.Chunk;

/**
 * Non-blocking river material pass run at the end of biome feature generation.
 *
 * <p>The heightfield and river masks are generated by {@link MassFluxRiverCarver}.
 * This class only decorates the already-generated chunk with water, waterlogged
 * stream layers and irregular bank layers. It never starts Terrain Diffusion
 * inference from generation callbacks.</p>
 */
public final class RiverFluidPlacement {
    private static final int CHUNK_SIZE = 16;

    private RiverFluidPlacement() {
    }

    /**
     * Called from ChunkGeneratorMixin after vanilla biome features have been placed.
     * This is intentionally not wired to ServerChunkEvents.CHUNK_GENERATE : doing the
     * work there caused visible late edits and chunk-load stalls.
     */
    public static void onGenerateFeatures(StructureWorldAccess world, Chunk chunk) {
        if (world.toServerWorld().getRegistryKey() != World.OVERWORLD) {
            return;
        }

        ChunkPos chunkPos = chunk.getPos();
        int chunkStartX = chunkPos.getStartX();
        int chunkStartZ = chunkPos.getStartZ();

        int tileSize = TerrainDiffusionConfig.tileSize();
        int tileShift = Integer.numberOfTrailingZeros(tileSize);

        int tileX = chunkStartX >> tileShift;
        int tileZ = chunkStartZ >> tileShift;

        int tileStartX = tileX << tileShift;
        int tileStartZ = tileZ << tileShift;
        int tileEndX = tileStartX + tileSize;
        int tileEndZ = tileStartZ + tileSize;

        HeightmapData data = LocalTerrainProvider.getReadyHeightmap(tileStartZ, tileStartX, tileEndZ, tileEndX);
        if (data == null || data.heightmap == null || data.biomeIds == null || data.riverCells == null) {
            return;
        }

        int minY = world.getBottomY();
        int maxY = world.getBottomY() + world.getHeight() - 1;
        BlockPos.Mutable pos = new BlockPos.Mutable();

        for (int dz = 0; dz < CHUNK_SIZE; dz++) {
            int worldZ = chunkStartZ + dz;
            int localZ = worldZ - tileStartZ;
            if (localZ < 0 || localZ >= data.height) continue;

            for (int dx = 0; dx < CHUNK_SIZE; dx++) {
                int worldX = chunkStartX + dx;
                int localX = worldX - tileStartX;
                if (localX < 0 || localX >= data.width) continue;

                byte riverClass = data.riverCells[localZ][localX];
                if (riverClass == MassFluxRiverCarver.RIVER_NONE) continue;

                // Drop isolated one-off pixels. These were showing up as lone source puddles
                // and stray waterlogged plates away from visible streams.
                if (riverClass >= MassFluxRiverCarver.RIVER_TINY_STREAM
                        && riverClass < MassFluxRiverCarver.RIVER_FULL_RIVER
                        && isIsolatedMinorFlow(data, localZ, localX)) {
                    continue;
                }

                int expectedSurfaceY = HeightConverter.convertToMinecraftHeight(data.heightmap[localZ][localX]);
                int surfaceY = findActualTerrainSurfaceY(world, chunk, pos, worldX, worldZ, expectedSurfaceY, minY, maxY);

                if (riverClass == MassFluxRiverCarver.RIVER_BANK) {
                    placeBankLayer(world, chunk, data, pos, worldX, surfaceY, worldZ, localZ, localX, minY, maxY);
                } else if (riverClass == MassFluxRiverCarver.RIVER_FULL_RIVER) {
                    placeFullRiver(world, chunk, data, pos, worldX, surfaceY, worldZ, localZ, localX, minY, maxY);
                } else {
                    placeMinorStream(world, chunk, data, pos, worldX, surfaceY, worldZ, localZ, localX, riverClass, minY, maxY);
                }
            }
        }
    }

    private static void placeMinorStream(
            StructureWorldAccess world,
            Chunk chunk,
            HeightmapData data,
            BlockPos.Mutable pos,
            int worldX,
            int surfaceY,
            int worldZ,
            int localZ,
            int localX,
            byte riverClass,
            int minY,
            int maxY
    ) {
        int bedY = clamp(surfaceY, minY, maxY);
        int layerY = clamp(bedY + 1, minY, maxY);

        // Clean after vegetation/features have spawned. Minor streams are sub-block
        // waterlogged layers so any plant/tree column above them must be removed.
        cleanPlacementColumn(world, chunk, pos, worldX, worldZ, layerY, layerY + 8, minY, maxY, true);

        BlockState baseState = chooseBedBaseBlock(data, localZ, localX, worldX, worldZ, riverClass).getDefaultState();
        pos.set(worldX, bedY, worldZ);
        chunk.setBlockState(pos, baseState, 0);

        int h = hash2(worldX, worldZ);
        int layers = riverClass == MassFluxRiverCarver.RIVER_TINY_STREAM
                ? 1 + ((h & 7) == 0 ? 1 : 0)
                : 2 + ((h & 3) == 0 ? 1 : 0);

        LayeredBlock bedMaterial = chooseBedMaterial(data, localZ, localX, worldX, worldZ, riverClass);
        pos.set(worldX, layerY, worldZ);
        if (canReplaceAt(world, chunk, pos)) {
            chunk.setBlockState(pos, layerState(bedMaterial, layers, true), 0);
        }
    }

    private static void placeFullRiver(
            StructureWorldAccess world,
            Chunk chunk,
            HeightmapData data,
            BlockPos.Mutable pos,
            int worldX,
            int surfaceY,
            int worldZ,
            int localZ,
            int localX,
            int minY,
            int maxY
    ) {
        int bedY = clamp(surfaceY, minY, maxY);
        int waterY = clamp(bedY + 1, minY, maxY);

        // For full rivers do not put a layer block under the source water. That made
        // layers visually float and kept grass-side overlays visible through water.
        cleanPlacementColumn(world, chunk, pos, worldX, worldZ, waterY, waterY + 10, minY, maxY, true);

        BlockState baseState = chooseBedBaseBlock(data, localZ, localX, worldX, worldZ, MassFluxRiverCarver.RIVER_FULL_RIVER).getDefaultState();
        pos.set(worldX, bedY, worldZ);
        chunk.setBlockState(pos, baseState, 0);

        pos.set(worldX, waterY, worldZ);
        if (canReplaceAt(world, chunk, pos)) {
            chunk.setBlockState(pos, Blocks.WATER.getDefaultState(), 0);
        }
    }

    private static void placeBankLayer(
            StructureWorldAccess world,
            Chunk chunk,
            HeightmapData data,
            BlockPos.Mutable pos,
            int worldX,
            int surfaceY,
            int worldZ,
            int localZ,
            int localX,
            int minY,
            int maxY
    ) {
        int nearbyWater = countNearbyWaterClasses(data, localZ, localX);
        if (nearbyWater <= 0) return;

        int h = hash2(worldX, worldZ);
        // Avoid a uniform outline. Inner banks are dense outer banks are patchy.
        if (nearbyWater <= 1 && (h & 7) != 0) return;
        if (nearbyWater == 2 && (h & 3) == 0) return;
        if (nearbyWater >= 3 && (h & 15) == 0) return;

        int layerY = clamp(surfaceY + 1, minY, maxY);
        cleanPlacementColumn(world, chunk, pos, worldX, worldZ, layerY, layerY + 3, minY, maxY, false);

        // Inner banks get a real substrate surface. This hides grass overlays at the
        // river edge and makes the dressing read as a natural disturbed bank.
        if (nearbyWater >= 2 || (h & 3) == 0) {
            pos.set(worldX, surfaceY, worldZ);
            chunk.setBlockState(pos, chooseBankBaseBlock(data, localZ, localX, worldX, worldZ).getDefaultState(), 0);
        }

        int layers = nearbyWater >= 5 ? 3 : nearbyWater >= 2 ? 2 : 1;
        if ((h & 9) == 0) layers++;
        LayeredBlock material = chooseBankMaterial(data, localZ, localX, worldX, worldZ);

        pos.set(worldX, layerY, worldZ);
        if (canReplaceAt(world, chunk, pos)) {
            chunk.setBlockState(pos, layerState(material, layers, false), 0);
        }
    }

    private static int findActualTerrainSurfaceY(
            StructureWorldAccess world,
            Chunk chunk,
            BlockPos.Mutable pos,
            int worldX,
            int worldZ,
            int expectedSurfaceY,
            int minY,
            int maxY
    ) {
        int start = clamp(expectedSurfaceY + 18, minY, maxY);
        int end = clamp(expectedSurfaceY - 26, minY, maxY);
        for (int y = start; y >= end; y--) {
            pos.set(worldX, y, worldZ);
            BlockState state = chunk.getBlockState(pos);
            if (isTerrainSurface(world, pos, state)) {
                return y;
            }
        }
        return clamp(expectedSurfaceY, minY, maxY);
    }

    private static void cleanPlacementColumn(
            StructureWorldAccess world,
            Chunk chunk,
            BlockPos.Mutable pos,
            int worldX,
            int worldZ,
            int y0,
            int y1,
            int minY,
            int maxY,
            boolean removeTrees
    ) {
        int from = clamp(y0, minY, maxY);
        int to = clamp(y1, minY, maxY);
        for (int y = from; y <= to; y++) {
            pos.set(worldX, y, worldZ);
            BlockState state = chunk.getBlockState(pos);
            if (state.isAir()) continue;
            if (shouldClearAboveRiver(world, pos, state, removeTrees)) {
                chunk.setBlockState(pos, Blocks.AIR.getDefaultState(), 0);
            }
        }
    }

    private static boolean canReplaceAt(StructureWorldAccess world, Chunk chunk, BlockPos.Mutable pos) {
        BlockState current = chunk.getBlockState(pos);
        return current.isAir()
                || !current.getFluidState().isEmpty()
                || current.getBlock() instanceof LayeredBlock
                || shouldClearAboveRiver(world, pos, current, true);
    }

    private static boolean shouldClearAboveRiver(StructureWorldAccess world, BlockPos pos, BlockState state, boolean removeTrees) {
        if (state.isAir()) return false;
        if (!state.getFluidState().isEmpty()) return true;
        if (state.getBlock() instanceof LayeredBlock) return true;
        if (removeTrees && (state.isIn(BlockTags.LOGS) || state.isIn(BlockTags.LEAVES))) return true;
        return !state.isSolidBlock(world, pos);
    }

    private static boolean isTerrainSurface(StructureWorldAccess world, BlockPos pos, BlockState state) {
        return !state.isAir()
                && state.getFluidState().isEmpty()
                && !(state.getBlock() instanceof LayeredBlock)
                && !state.isIn(BlockTags.LOGS)
                && !state.isIn(BlockTags.LEAVES)
                && state.isSolidBlock(world, pos);
    }

    private static BlockState layerState(LayeredBlock block, int layers, boolean waterlogged) {
        int clampedLayers = Math.max(1, Math.min(7, layers));
        boolean canWaterlog = clampedLayers >= 2 && clampedLayers <= 6;
        return block.getDefaultState()
                .with(LayeredBlock.LAYERS, clampedLayers)
                .with(LayeredBlock.WATERLOGGED, waterlogged && canWaterlog)
                .with(LayeredBlock.SNOWY, false);
    }

    private static LayeredBlock chooseBedMaterial(HeightmapData data, int z, int x, int worldX, int worldZ, byte riverClass) {
        short biome = data.biomeIds[z][x];
        int h = hash2(worldX, worldZ);

        if (biome == 26) return (h & 3) == 0 ? ModBlocks.CLAY_LAYER : ModBlocks.RED_SAND_LAYER;
        if (biome == 5 || biome == 17) return (h & 3) == 0 ? ModBlocks.GRAVEL_LAYER : ModBlocks.SAND_LAYER;
        if (biome == 19 || biome == 33 || biome == 35) return (h & 3) == 0 ? ModBlocks.STONE_LAYER : ModBlocks.GRAVEL_LAYER;

        if (riverClass == MassFluxRiverCarver.RIVER_TINY_STREAM) {
            return (h & 7) == 0 ? ModBlocks.SAND_LAYER : ModBlocks.GRAVEL_LAYER;
        }
        if (riverClass == MassFluxRiverCarver.RIVER_SMALL_STREAM) {
            return (h & 3) == 0 ? ModBlocks.SAND_LAYER : ModBlocks.GRAVEL_LAYER;
        }
        return (h & 7) == 0 ? ModBlocks.CLAY_LAYER : ModBlocks.GRAVEL_LAYER;
    }

    private static LayeredBlock chooseBankMaterial(HeightmapData data, int z, int x, int worldX, int worldZ) {
        short biome = data.biomeIds[z][x];
        int h = hash2(worldX, worldZ);

        if (biome == 26) return (h & 1) == 0 ? ModBlocks.RED_SAND_LAYER : ModBlocks.COARSE_DIRT_LAYER;
        if (biome == 5 || biome == 17) return (h & 3) == 0 ? ModBlocks.COARSE_DIRT_LAYER : ModBlocks.SAND_LAYER;
        if (biome == 19 || biome == 33 || biome == 35) return (h & 3) == 0 ? ModBlocks.GRAVEL_LAYER : ModBlocks.STONE_LAYER;
        if (biome == 6 || biome == 23) return (h & 3) == 0 ? ModBlocks.CLAY_LAYER : ModBlocks.DIRT_LAYER;
        return (h & 3) == 0 ? ModBlocks.COARSE_DIRT_LAYER : ModBlocks.DIRT_LAYER;
    }

    private static Block chooseBedBaseBlock(HeightmapData data, int z, int x, int worldX, int worldZ, byte riverClass) {
        short biome = data.biomeIds[z][x];
        int h = hash2(worldX, worldZ);
        if (biome == 26) return (h & 3) == 0 ? Blocks.CLAY : Blocks.RED_SAND;
        if (biome == 5 || biome == 17) return (h & 3) == 0 ? Blocks.GRAVEL : Blocks.SAND;
        if (biome == 19 || biome == 33 || biome == 35) return (h & 3) == 0 ? Blocks.STONE : Blocks.GRAVEL;
        if (riverClass == MassFluxRiverCarver.RIVER_FULL_RIVER && (h & 7) == 0) return Blocks.CLAY;
        return Blocks.GRAVEL;
    }

    private static Block chooseBankBaseBlock(HeightmapData data, int z, int x, int worldX, int worldZ) {
        short biome = data.biomeIds[z][x];
        int h = hash2(worldX, worldZ);
        if (biome == 26) return (h & 1) == 0 ? Blocks.RED_SAND : Blocks.COARSE_DIRT;
        if (biome == 5 || biome == 17) return (h & 3) == 0 ? Blocks.COARSE_DIRT : Blocks.SAND;
        if (biome == 19 || biome == 33 || biome == 35) return (h & 3) == 0 ? Blocks.GRAVEL : Blocks.STONE;
        if (biome == 6 || biome == 23) return (h & 3) == 0 ? Blocks.CLAY : Blocks.DIRT;
        return (h & 3) == 0 ? Blocks.COARSE_DIRT : Blocks.DIRT;
    }

    private static boolean isIsolatedMinorFlow(HeightmapData data, int z, int x) {
        int adjacent = 0;
        int radiusTwo = 0;
        for (int dz = -2; dz <= 2; dz++) {
            int zz = z + dz;
            if (zz < 0 || zz >= data.height) continue;
            for (int dx = -2; dx <= 2; dx++) {
                int xx = x + dx;
                if (xx < 0 || xx >= data.width || (dz == 0 && dx == 0)) continue;
                if (data.riverCells[zz][xx] >= MassFluxRiverCarver.RIVER_TINY_STREAM) {
                    radiusTwo++;
                    if (Math.abs(dz) <= 1 && Math.abs(dx) <= 1) adjacent++;
                }
            }
        }
        return adjacent < 2 || radiusTwo < 3;
    }

    private static int countNearbyWaterClasses(HeightmapData data, int z, int x) {
        int count = 0;
        for (int dz = -4; dz <= 4; dz++) {
            int zz = z + dz;
            if (zz < 0 || zz >= data.height) continue;
            for (int dx = -4; dx <= 4; dx++) {
                int xx = x + dx;
                if (xx < 0 || xx >= data.width) continue;
                if (data.riverCells[zz][xx] >= MassFluxRiverCarver.RIVER_TINY_STREAM) {
                    count++;
                }
            }
        }
        return count;
    }

    private static int hash2(int x, int z) {
        int h = x * 0x9E3779B9 + z * 0x85EBCA6B;
        h ^= h >>> 16;
        h *= 0x7FEB352D;
        h ^= h >>> 15;
        h *= 0x846CA68B;
        h ^= h >>> 16;
        return h;
    }

    private static int clamp(int v, int lo, int hi) {
        return Math.max(lo, Math.min(hi, v));
    }
}
