modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL=""

[[mods]]
modId="${fml_mod_id}"
namespace="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
credits="${credits}"
description='''${description}'''

[[mixins]]
config="${mod_id}.mixins.json"
[[mixins]]
config="${mod_id}.client.mixins.json"
[[mixins]]
config="${mod_id}.neoforge.mixins.json"

[[dependencies.${fml_mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${fml_mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
