#!/usr/bin/env bash
# Build the hybrid libs/onnxruntime-rocm.jar that the -rocm variant depends on.
#
# Combines:
#   - ai.onnxruntime Java classes (Maven Central, com.microsoft.onnxruntime:onnxruntime:1.21.0)
#   - libonnxruntime4j_jni.so recompiled from upstream sources with -DUSE_ROCM
#   - libonnxruntime.so + libonnxruntime_providers_rocm.so + libonnxruntime_providers_shared.so
#     from AMD's onnxruntime-rocm Python wheel (Python 3.12 / ROCm 6.4.4)
#   - librocm_smi64-*.so.7.7.60404 (auditwheel-bundled rocm-smi dependency)
#
# Build deps on the host:
#   - python3.12 + python3.12-devel (for venv to install the wheel)
#   - java-21-openjdk-devel (JDK with javac for header generation)
#   - patchelf, gcc, zip, curl, unzip
#   - ROCm 6.4 dev headers and libs system-installed (libamdhip64, libMIOpen, etc.)
#
# Pin everything via versioned URLs so reruns yield byte-identical output (modulo
# patchelf which encodes our $ORIGIN rpath patches).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_JAR="$ROOT/libs/onnxruntime-rocm.jar"

ORT_VERSION=1.21.0
ROCM_REL=rocm-rel-6.4.4
WHEEL_URL="https://repo.radeon.com/rocm/manylinux/${ROCM_REL}/onnxruntime_rocm-1.21.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"
MAVEN_JAR_URL="https://repo1.maven.org/maven2/com/microsoft/onnxruntime/onnxruntime/${ORT_VERSION}/onnxruntime-${ORT_VERSION}.jar"
ORT_SRC_TAG="v${ORT_VERSION}"

WORK="$(mktemp -d -t td-rocm-jar-XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
echo "[*] work dir: $WORK"

echo "[1/6] downloading Maven CPU jar (Java classes + reference JNI)"
curl -sfL -o "$WORK/onnxruntime-${ORT_VERSION}.jar" "$MAVEN_JAR_URL"

echo "[2/6] extracting Python wheel for ROCm-built native libs"
curl -sfL -o "$WORK/onnxruntime_rocm.whl" "$WHEEL_URL"
mkdir -p "$WORK/wheel"
unzip -q "$WORK/onnxruntime_rocm.whl" -d "$WORK/wheel"

echo "[3/6] cloning ONNX Runtime sources at ${ORT_SRC_TAG} (for JNI rebuild)"
git clone --branch "$ORT_SRC_TAG" --depth 1 \
    https://github.com/microsoft/onnxruntime.git "$WORK/onnxruntime-src" >/dev/null 2>&1

echo "[4/6] rebuilding libonnxruntime4j_jni.so with -DUSE_ROCM"
export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-21-openjdk}"
mkdir -p "$WORK/jni-build"
cat > "$WORK/jni-build/onnxruntime_config.h" <<EOF
// Generated by build-onnxruntime-rocm-jar.sh
#pragma once
#define ORT_BUILD_INFO "rocm-hybrid-${ORT_VERSION}"
#define ORT_VERSION "${ORT_VERSION}"
EOF
javac -d "$WORK/jni-build/java-classes" -h "$WORK/jni-build" \
    "$WORK/onnxruntime-src/java/src/main/java"/ai/onnxruntime/*.java \
    "$WORK/onnxruntime-src/java/src/main/java"/ai/onnxruntime/providers/*.java \
    "$WORK/onnxruntime-src/java/src/main/jvm"/ai/onnxruntime/platform/*.java
C_SRCS=$(ls "$WORK/onnxruntime-src/java/src/main/native"/*.c | grep -v Training)
gcc -shared -fPIC -O2 -DUSE_ROCM=1 \
    -I "$JAVA_HOME/include" -I "$JAVA_HOME/include/linux" \
    -I "$WORK/jni-build" \
    -I "$WORK/onnxruntime-src/include" \
    -I "$WORK/onnxruntime-src/include/onnxruntime/core/session" \
    $C_SRCS \
    -L "$WORK/wheel/onnxruntime/capi" \
    -Wl,-rpath,'$ORIGIN' \
    -l:libonnxruntime.so.${ORT_VERSION} \
    -o "$WORK/jni-build/libonnxruntime4j_jni.so"

echo "[5/6] assembling jar contents"
mkdir -p "$WORK/jar-stage"
( cd "$WORK/jar-stage" && unzip -q "$WORK/onnxruntime-${ORT_VERSION}.jar" )
NATIVE_DIR="$WORK/jar-stage/ai/onnxruntime/native/linux-x64"
cp -f "$WORK/wheel/onnxruntime/capi/libonnxruntime.so.${ORT_VERSION}" "$NATIVE_DIR/libonnxruntime.so"
cp -f "$WORK/wheel/onnxruntime/capi/libonnxruntime_providers_rocm.so"  "$NATIVE_DIR/"
cp -f "$WORK/wheel/onnxruntime/capi/libonnxruntime_providers_shared.so" "$NATIVE_DIR/"
cp -f "$WORK/wheel/onnxruntime_rocm.libs"/librocm_smi64-*.so.* "$NATIVE_DIR/"
cp -f "$WORK/jni-build/libonnxruntime4j_jni.so" "$NATIVE_DIR/"
# Re-rpath the rocm provider so it finds the bundled rocm-smi in $ORIGIN.
patchelf --set-rpath '$ORIGIN' "$NATIVE_DIR/libonnxruntime_providers_rocm.so"

echo "[6/6] packaging $OUT_JAR"
rm -f "$OUT_JAR"
( cd "$WORK/jar-stage" && zip -qr "$OUT_JAR" . )
ls -la "$OUT_JAR"
echo "[done]"
